const STORAGE_KEY = 'lisboa-signal-decisions-v3';
const LEGACY_KEYS = ['lisbon-radar-decisions-v2', 'lisbon-radar-decisions'];
const TZ = 'Europe/Lisbon';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const stored = localStorage.getItem(STORAGE_KEY) || LEGACY_KEYS.map(key => localStorage.getItem(key)).find(Boolean) || '{}';
const state = {events:[],sources:[],status:{},surface:{surface:'private'},decisions:JSON.parse(stored),horizon:'today',topics:new Set(),range:{start:0,end:0}};

function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function safeUrl(value=''){try{const url=new URL(value,location.origin);return ['http:','https:'].includes(url.protocol)?url.href:'';}catch{return '';}}
function lisbonDay(raw){const date=raw instanceof Date?raw:new Date(raw);if(Number.isNaN(date.valueOf()))return '';return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:TZ}).format(date);}
function addDays(day,amount){const base=new Date(`${day}T12:00:00Z`);base.setUTCDate(base.getUTCDate()+amount);return base.toISOString().slice(0,10);}
function dayOffset(raw){const today=lisbonDay(new Date());const day=lisbonDay(raw);return Math.round((new Date(`${day}T12:00:00Z`)-new Date(`${today}T12:00:00Z`))/86400000);}
function fmtDate(raw){const date=new Date(raw);if(Number.isNaN(date.valueOf()))return 'DATE TBC';return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:TZ}).format(date).replace(',',' ·').toUpperCase();}
function shortDay(offset){if(offset===0)return 'TODAY';if(offset===1)return 'TOMORROW';return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',timeZone:TZ}).format(new Date(`${addDays(lisbonDay(new Date()),offset)}T12:00:00Z`)).toUpperCase();}
function isPrivate(){return state.surface.surface!=='public';}
function eventScore(event){return Number(isPrivate()?event.score:event.public_signal||0);}
function isFuture(event){const end=new Date(event.end||event.start).valueOf();return Number.isFinite(end)&&end>Date.now();}
function activeWindow(){const today=lisbonDay(new Date());return {start:addDays(today,state.range.start),end:addDays(today,state.range.end)};}
function overlaps(event,range){const start=lisbonDay(event.start),end=lisbonDay(event.end||event.start)||start;return Boolean(start)&&start<=range.end&&end>=range.start;}

async function fetchJson(primary,fallback){try{const response=await fetch(primary);if(!response.ok)throw new Error(String(response.status));return await response.json();}catch(error){if(!fallback)throw error;const response=await fetch(fallback);if(!response.ok)throw error;return response.json();}}
async function load(){
  const requests=[fetchJson('/api/surface').catch(()=>({surface:'public',writes:false,private_sources:false,delivery:false,learning:false})),fetchJson('/api/events','data/public/events.json'),fetchJson('/api/sources','data/public/sources.json'),fetchJson('/api/status','data/public/status.json')];
  const [surface,events,sources,status]=await Promise.all(requests);
  Object.assign(state,{surface,events:Array.isArray(events)?events:[],sources:Array.isArray(sources)?sources:[],status});
  applySurface();renderAll();
}

function applySurface(){
  document.body.dataset.surface=state.surface.surface;
  $('#surface-label').textContent=isPrivate()?'PRIVATE FIT LAB':'PUBLIC CITY GUIDE';
  $('#signal-score-label').textContent=isPrivate()?'FIT':'SIGNAL';
  if(!isPrivate()){$('#sort').value='soonest';$('#provenance option[value="telegram-signal"]')?.remove();$('#route-copy').textContent='A public, read-only edit of verified events in Lisbon. Personal fit and Telegram stay private.';}
}

function presetRange(horizon){
  if(horizon==='today')return [0,0];if(horizon==='tomorrow')return [1,1];if(horizon==='3d')return [0,2];if(horizon==='7d')return [0,6];if(horizon==='30d')return [0,29];
  const weekday=Number(new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:TZ}).formatToParts(new Date()).find(part=>part.type==='weekday')?.value&&['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:TZ}).format(new Date())));
  const saturday=weekday===0?6:Math.max(0,6-weekday);return [saturday,saturday+1];
}

function filtered({includeHidden=false,decisionOnly=false}={}){
  const q=$('#search').value.trim().toLowerCase(),min=isPrivate()?Number($('#fit-min').value):0,max=isPrivate()?Number($('#fit-max').value):100,source=$('#provenance').value,range=activeWindow();
  const items=state.events.filter(event=>{const decision=state.decisions[event.id],text=`${event.title||''} ${event.summary||''} ${event.venue||''} ${(event.tags||[]).join(' ')}`.toLowerCase();if(!isFuture(event)||!overlaps(event,range)||eventScore(event)<min||eventScore(event)>max)return false;if(q&&!text.includes(q))return false;if(source!=='all'&&event.provenance!==source)return false;if(state.topics.size&&![...state.topics].some(topic=>(event.tags||[]).includes(topic)))return false;if(!includeHidden&&decision==='hide')return false;if(decisionOnly&&!['watch','queue'].includes(decision))return false;return true;});
  const sort=$('#sort').value;items.sort((a,b)=>sort==='soonest'||(!isPrivate()&&sort!=='signal')?new Date(a.start)-new Date(b.start):eventScore(b)-eventScore(a)||new Date(a.start)-new Date(b.start));return items;
}

function fitReceipt(event){const data=event.learning_breakdown||{};if(!data.active)return `BASE FIT ${event.base_score??event.score??'–'} · learning starts after ${data.minimum_feedback||3} votes`;return `BASE ${event.base_score} · LEARNED ${event.learning_delta>=0?'+':''}${event.learning_delta} · TOPIC ${data.topic} · SOURCE ${data.source} · ${String(data.time_bucket||'').toUpperCase()} ${data.time}`;}

function card(event,{priority=false}={}){
  const fragment=$('#event-template').content.cloneNode(true),root=fragment.querySelector('.event-card'),poster=root.querySelector('.poster'),image=poster.querySelector('img'),video=poster.querySelector('video');root.dataset.id=event.id;
  const imageUrl=event.image_url||'',tag=(event.match_tags?.[0]||event.tags?.[0]||'lisboa').replace(/-/g,' ');poster.querySelector('.poster-fallback span').textContent=tag;poster.querySelector('.poster-kind').textContent=event.needs_confirmation?'NEEDS CONFIRMATION':event.provenance==='public-jsonld'?'LIVE SOURCE':'CURATED SOURCE';
  if(priority)image.loading='eager';
  if(/\.(mp4|webm|mov)(?:\?|$)/i.test(imageUrl)){video.addEventListener('loadeddata',()=>poster.classList.add('has-image'));video.addEventListener('error',()=>video.removeAttribute('src'));video.src=imageUrl;}else if(imageUrl){image.alt=`Poster for ${event.title}`;image.addEventListener('load',()=>poster.classList.add('has-image'));image.addEventListener('error',()=>image.removeAttribute('src'));image.src=imageUrl;}
  root.querySelector('.score-badge b').textContent=eventScore(event);root.querySelector('.score-badge small').textContent=isPrivate()?'FIT':'SIGNAL';root.querySelector('.date').textContent=fmtDate(event.start);root.querySelector('.tier').textContent=`${event.source_tier||'B'} · ${event.source_name||'PUBLIC SOURCE'}`;root.querySelector('h3').textContent=event.title;root.querySelector('.summary').textContent=event.summary||'Details are available at the original source.';root.querySelector('.fit-receipt').textContent=fitReceipt(event);root.querySelector('.venue').textContent=event.venue||'VENUE TBC';root.querySelector('.price').textContent=event.price||'DETAILS TBC';root.querySelector('.tags').innerHTML=(event.match_tags?.length?event.match_tags:event.tags||[]).slice(0,5).map(item=>`<span>#${escapeHtml(item)}</span>`).join('');
  const link=root.querySelector('.event-link'),url=safeUrl(event.url);if(url)link.href=url;else link.remove();root.querySelector('.why')?.addEventListener('click',()=>root.classList.toggle('explaining'));
  root.querySelectorAll('[data-action]').forEach(button=>{button.classList.toggle('selected',state.decisions[event.id]===button.dataset.action);button.addEventListener('click',()=>decide(event.id,button.dataset.action));});
  root.querySelectorAll('[data-feedback]').forEach(button=>button.addEventListener('click',()=>feedback(event.id,button.dataset.feedback,button)));
  return fragment;
}

function renderHero(items){const top=items[0],visual=$('#signal-visual');if(!top){$('#signal-title').textContent='No signals in this window';$('#signal-copy').textContent='Expand the date range or lower the threshold.';$('#signal-score').textContent='–';visual.style.backgroundImage='';$('#signal-link').removeAttribute('href');return;}$('#signal-title').textContent=top.title;$('#signal-copy').textContent=`${fmtDate(top.start)} · ${top.venue||'venue TBC'}. ${isPrivate()?(top.reason||top.summary||''):(top.summary||'')}`;$('#signal-score').textContent=eventScore(top);$('#signal-link').href=safeUrl(top.url)||'#';const img=top.image_url&&!/\.(mp4|webm|mov)(?:\?|$)/i.test(top.image_url)?top.image_url:'';visual.style.backgroundImage=img?`url("${String(img).replace(/"/g,'%22')}")`:'';}
function renderReceipt(){const root=$('#source-receipt'),generated=new Date(state.status.generated_at),observed=Number.isFinite(generated.valueOf()),fresh=observed&&Date.now()-generated.valueOf()<8*3600000;root.dataset.evidenceState=observed?'observed':'unobserved';root.querySelector('.evidence-receipt__label').textContent=observed?(fresh?'SOURCES FRESH':'REFRESH DUE'):'UNOBSERVED';root.querySelector('.evidence-receipt__count').textContent=state.status.event_count??state.events.length;root.querySelector('.evidence-receipt__detail').textContent=isPrivate()?`${state.events.length} future events · ${state.status.learning?.feedback_count||0} taste votes.`:`${state.events.length} verified public events. Personal sources excluded.`;root.querySelector('.evidence-receipt__source').textContent=`SOURCE RECEIPT · ${observed?fmtDate(generated):'NONE'}`;}
function renderTopics(){const counts={};state.events.filter(isFuture).forEach(event=>(event.tags||[]).forEach(tag=>counts[tag]=(counts[tag]||0)+1));$('#topic-rail').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,18).map(([tag,count])=>`<button data-topic="${escapeHtml(tag)}" class="${state.topics.has(tag)?'selected':''}">#${escapeHtml(tag)} <small>${count}</small></button>`).join('');$$('[data-topic]').forEach(button=>button.addEventListener('click',()=>{const tag=button.dataset.topic;state.topics.has(tag)?state.topics.delete(tag):state.topics.add(tag);renderAll();}));}
function renderEvents(items){const list=$('#event-list');list.innerHTML='';items.forEach((event,index)=>list.append(card(event,{priority:index<6})));$('#empty').classList.toggle('hidden',Boolean(items.length));$('#metric-visible').textContent=items.length;$('#results-copy').textContent=`${items.length} SIGNAL${items.length===1?'':'S'} · ${shortDay(state.range.start)} → ${shortDay(state.range.end)}`;}
function renderSources(){$('#source-grid').innerHTML=state.sources.map(source=>{const url=safeUrl(source.url);return `<article class="source-card"><header><span class="source-state"><i></i>${escapeHtml(source.status||'REGISTERED')}</span><b>${escapeHtml(source.tier||'B')}</b></header><h3>${escapeHtml(source.name)}</h3><p>${escapeHtml(source.notes||source.source_type||'public source')}</p>${url?`<a href="${escapeHtml(url)}" target="_blank" rel="noreferrer">OPEN SOURCE ↗</a>`:''}</article>`;}).join('');}
function renderDecisions(){if(!isPrivate())return;const saved=state.events.filter(event=>isFuture(event)&&['watch','queue'].includes(state.decisions[event.id])).sort((a,b)=>new Date(a.start)-new Date(b.start)),list=$('#decision-list');list.innerHTML='';saved.forEach(event=>list.append(card(event)));if(!saved.length)list.innerHTML='<section class="empty"><b>NOTHING SAVED YET</b><p>Save or queue an event from the radar.</p></section>';const hidden=state.events.filter(event=>isFuture(event)&&state.decisions[event.id]==='hide');$('#hidden-list').innerHTML=hidden.map(event=>`<button data-restore="${escapeHtml(event.id)}"><span>${escapeHtml(fmtDate(event.start))}</span><b>${escapeHtml(event.title)}</b><small>RESTORE</small></button>`).join('');$$('[data-restore]').forEach(button=>button.addEventListener('click',()=>decide(button.dataset.restore,'hide')));$('#saved-count').textContent=saved.length;}
function renderAll(){const generated=new Date(state.status.generated_at);$('#generated').textContent=Number.isFinite(generated.valueOf())?`UPDATED ${fmtDate(generated)}`:'NO RECEIPT';$('#today-label').textContent=`LISBOA · ${new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:TZ}).format(new Date()).toUpperCase()}`;$('#metric-events').textContent=state.status.event_count??state.events.length;$('#metric-sources').textContent=state.status.source_count??state.sources.length;$('#metric-previews').textContent=state.status.preview_count??state.events.filter(event=>event.image_url).length;$('#fit-min-label').textContent=$('#fit-min').value;$('#fit-max-label').textContent=$('#fit-max').value;$('#day-start-label').textContent=shortDay(state.range.start);$('#day-end-label').textContent=shortDay(state.range.end);const items=filtered();renderReceipt();renderTopics();renderHero(items);renderEvents(items);renderSources();renderDecisions();}

let toastTimer;function toast(message,undo){const root=$('#toast');root.innerHTML=`${escapeHtml(message)}${undo?' <button>UNDO</button>':''}`;root.classList.add('visible');if(undo)root.querySelector('button').addEventListener('click',()=>{undo();root.classList.remove('visible');});clearTimeout(toastTimer);toastTimer=setTimeout(()=>root.classList.remove('visible'),4200);}
function decide(id,action){const previous=state.decisions[id];state.decisions[id]=previous===action?undefined:action;if(!state.decisions[id])delete state.decisions[id];localStorage.setItem(STORAGE_KEY,JSON.stringify(state.decisions));LEGACY_KEYS.forEach(key=>localStorage.removeItem(key));renderAll();if(['watch','hide'].includes(action)&&previous!==action)feedback(id,action==='watch'?'save':'hide',null,true);toast({watch:'Saved to your shortlist',queue:'Queued locally – no calendar write',hide:'Hidden on this device'}[action]||'Decision saved',()=>{if(previous)state.decisions[id]=previous;else delete state.decisions[id];localStorage.setItem(STORAGE_KEY,JSON.stringify(state.decisions));renderAll();});}
async function feedback(eventId,action,button,silent=false){if(!isPrivate())return;if(button)button.disabled=true;try{const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_id:eventId,action})});const data=await response.json();if(!response.ok)throw new Error(data.error||'feedback failed');if(!silent)toast(action==='love'?'Taste updated – more like this':'Taste updated – less like this');await load();}catch(error){if(!silent)toast(`Could not save feedback: ${error.message}`);}finally{if(button)button.disabled=false;}}
function setRange(start,end,horizon='custom'){state.range={start:Math.max(0,Math.min(start,end)),end:Math.min(90,Math.max(start,end))};state.horizon=horizon;$('#day-start').value=state.range.start;$('#day-end').value=state.range.end;$$('[data-horizon]').forEach(button=>button.classList.toggle('selected',button.dataset.horizon===horizon));renderAll();}

$$('[data-horizon]').forEach(button=>button.addEventListener('click',()=>{const [start,end]=presetRange(button.dataset.horizon);setRange(start,end,button.dataset.horizon);}));
$('#day-start').addEventListener('input',()=>setRange(Number($('#day-start').value),Math.max(Number($('#day-start').value),Number($('#day-end').value))));$('#day-end').addEventListener('input',()=>setRange(Math.min(Number($('#day-start').value),Number($('#day-end').value)),Number($('#day-end').value)));
$$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab,.view').forEach(item=>item.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.view}`).classList.add('active');history.replaceState(null,'',`#${tab.dataset.view}`);}));
['search','fit-min','fit-max','provenance','sort'].forEach(id=>$(`#${id}`).addEventListener('input',()=>{if(Number($('#fit-min').value)>Number($('#fit-max').value)){if(id==='fit-min')$('#fit-max').value=$('#fit-min').value;else $('#fit-min').value=$('#fit-max').value;}renderAll();}));
$('#reset-filters').addEventListener('click',()=>{$('#search').value='';$('#fit-min').value='45';$('#fit-max').value='100';$('#provenance').value='all';$('#sort').value=isPrivate()?'recommended':'soonest';state.topics.clear();renderAll();});
$('#refresh').addEventListener('click',async()=>{const button=$('#refresh');button.disabled=true;try{await fetch('/api/refresh',{method:'POST'});await load();toast('Radar refreshed');}catch(error){toast(`Refresh failed: ${error.message}`);}finally{button.disabled=false;}});
$('#clear-decisions').addEventListener('click',()=>{state.decisions={};localStorage.removeItem(STORAGE_KEY);renderAll();toast('Local state cleared');});
setRange(0,0,'today');load().catch(error=>{$('#generated').textContent=`DATA ERROR · ${error.message}`;$('#source-receipt').dataset.evidenceState='degraded';});
